pub mod adventurer_error;
pub mod app_error;
pub mod auth_error;
pub mod config_error;
pub mod db_error;
pub mod email_error;
pub mod guild_error;
pub mod hash_error;
pub mod http_error;
pub mod jwt_error;
pub mod message_error;
pub mod redis_error;
pub mod serde_error;
pub mod social_error;
pub mod task_error;
pub mod time_error;
pub mod uuid_error;
pub mod validation_error;

pub use app_error::{AppError, AppResult};
