name: Backend CI

on:
  push:
    paths:
      - 'be-rust/**'
  pull_request:
    paths:
      - 'be-rust/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: be-rust

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
